package model;

import java.time.LocalDateTime;

/**
 * Bill is a class used for logging of generated orders
 * @param orderId id of order
 * @param generatedDate date when the order was generated by the user
 */
public record Bill(Integer orderId, LocalDateTime generatedDate) {
}
